In [1]:
import torch
import torch.nn as nn
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

#Defining our linear Layer
linear_layer = nn.Linear( 
    in_features=3,
    out_features=2
)

#pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[0.3241, 0.3474]], grad_fn=<AddmmBackward0>)


In [2]:
#Sequential
model = nn.Sequential(
    nn.Linear(10, 8), #takes 10 inputs, 8 outputs
    nn.Linear(8,4), #takes 18 and outputs 20
    nn.Linear(4,5) 
)
total = 0 #getting the total number of parameters 
for parameter in model.parameters():
    total += parameter.numel()
print(total)

149


In [3]:
#Sigmoid Function - For binary classification
 
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9975]])


In [4]:
#Softmax - for CLASSIFICATION
 
input_tensor = torch.tensor([[4.3,6.1,2.3]])
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [ ]:
#Backpropagation
model = nn.Sequential(nn.Linear(16,8), 
                      nn. Linear(8,4),
                      nn.Linear(4,2))
#prediction = model(sample)
#Calculate the loss and gradients

NameError: name 'sample' is not defined

Tensor Data Set

Using a dataset

In [6]:
import pandas as pd
import numpy as np
import matplotlib as plt

df = pd.read_csv('imdb_movies.csv')
df.head()

names       date_x  score  \
0                    Creed III  03/02/2023    73.0   
1     Avatar: The Way of Water  12/15/2022    78.0   
2  The Super Mario Bros. Movie  04/05/2023    76.0   
3                      Mummies  01/05/2023    70.0   
4                    Supercell  03/17/2023    61.0   

                                           genre  \
0                                  Drama, Action   
1             Science Fiction, Adventure, Action   
2  Animation, Adventure, Family, Fantasy, Comedy   
3  Animation, Comedy, Family, Adventure, Fantasy   
4                                         Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   
2  While working underground to fix a water main,...   
3  Through a series of unfortunate events, three ...   
4  Good-hearted teenager William always lived in ...   

                                                crew  \
0  Michael B. Jordan, Adonis Creed, Tessa Thompso...   
1  Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...   
2  Chris Pratt, Mario (voice), Anya Taylor-Joy, P...   
3  Óscar Barberán, Thut (voice), Ana Esther Albor...   
4  Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...   

                    orig_title     status            orig_lang     budget_x  \
0                    Creed III   Released              English   75000000.0   
1     Avatar: The Way of Water   Released              English  460000000.0   
2  The Super Mario Bros. Movie   Released              English  100000000.0   
3                       Momias   Released   Spanish, Castilian   12300000.0   
4                    Supercell   Released              English   77000000.0   

        revenue country  
0  2.716167e+08      AU  
1  2.316795e+09      AU  
2  7.244590e+08      AU  
3  3.420000e+07      AU  
4  3.409420e+08      US

In [7]:
import torch
from torch.utils.data import TensorDataset


Training a neural network:
1. Create a Model
2. Choose a loss function
3. Define a dataset
4. Set an optimizer
5. Run a Training loop:
 - Calculate the loss(forward pass)
 - Compute Gradients(back propagation)
 - Updating model parameters

In [8]:
from torch.utils.data import TensorDataset, DataLoader
import torch.optim as optim

In [9]:
df_new = pd.read_csv('salary.csv')
df_new.head()
features = df_new.iloc[:, :-1]
target = df_new.iloc[:,-1]

In [10]:
df_new.head()

experience_level  employment_type  remote_ratio  company_size  \
0                 0                0           0.5             1   
1                 1                0           1.0             2   
2                 2                0           0.0             1   
3                 1                0           1.0             0   
4                 2                0           1.0             1   

   salary_in_usd  
0          0.036  
1          0.133  
2          0.234  
3          0.076  
4          0.170

In [11]:
X = features.to_numpy()
print(X)

[[0.  0.  0.5 1. ]
 [1.  0.  1.  2. ]
 [2.  0.  0.  1. ]
 [1.  0.  1.  0. ]
 [2.  0.  1.  1. ]]


In [12]:
y = target.to_numpy()
print(y)

[0.036 0.133 0.234 0.076 0.17 ]


In [13]:
dataset = TensorDataset(torch.tensor(X).float(),
                        torch.tensor(y).float())
dataloader = DataLoader(dataset, batch_size=4,shuffle=True)

In [14]:
#Create an MSE loss function
def mean_squared_loss(prediction, target):
    return np.mean((prediction-target)**2)

In [15]:
#Create the model

model = nn.Sequential(
    nn.Linear(4,2),
    nn.Linear(2,1)
)

In [ ]:
criterion = nn.MSELoss()    
# Prediction and target are float tensors
optimizer = optim.SGD(model.parameters(),lr=0.001)

In [17]:
#Training loop
num_epochs=4
for epoch in range(num_epochs):
    for data in dataloader:
        #Set Gradients to 0
        optimizer.zero_grad()
        ## Get feature and target from the data loader
        X, y = data
        pred = model(X)
        loss = criterion(pred, y)
        loss.backward()
        optimizer.step()

/home/robin-cpe/deactivate/envs/torch-gpu/lib/python3.10/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/robin-cpe/deactivate/envs/torch-gpu/lib/python3.10/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
