In [2]:
import torch
import torch.nn as nn
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

#Defining our linear Layer
linear_layer = nn.Linear( 
    in_features=3,
    out_features=2
)

#pass input through linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[-0.4210, -0.5676]], grad_fn=<AddmmBackward0>)


In [ ]:
#Sequential
model = nn.Sequential(
    nn.Linear(10, 8), #takes 10 inputs, 8 outputs
    nn.Linear(8,4), #takes 18 and outputs 20
    nn.Linear(4,5) 
)
total = 0 #getting the total number of parameters 
for parameter in model.parameters():
    total += parameter.numel()
print(total)

149


In [ ]:
#Sigmoid Function - For binary classification
 
input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9975]])


In [6]:
#Softmax - for CLASSIFICATION
 
input_tensor = torch.tensor([[4.3,6.1,2.3]])
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [ ]:
#Backpropagation
model = nn.Sequential(nn.Linear(16,8), 
                      nn. Linear(8,4),
                      nn.Linear(4,2))
prediction = model(sample)
#Calculate the loss and gradients